Creates Sentry Connector by DOit
doitsa/sentry-connector pull request #2
Opened 2018-07-13 14:16 UTC by luizalfredo23

2018-07-13 14:17 UTC, luizalfredo23 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[doitsa] Notificar erro no envio/consulta de remessa usando o Sentry](https://trello.com/c/WuVFOtrB/1081-doitsa-notificar-erro-no-envio-consulta-de-remessa-usando-o-sentry)

2018-07-16 14:50 UTC, hprange requested changes
@luizalfredo23 implementation is good. We need to improve the docs according to the comments. Let's take a look at this together.

2018-07-16 14:50 UTC, hprange commented on CHANGELOG.md
> +Example: Session ID expires after  30 days. http://github.com/mulesoft/sentry/issues/62
@luizalfredo23 this is the default content generated for this file, right? We need to enter the proper release information for this connector. Or leave it blank while no release has been published.

2018-07-16 14:50 UTC, hprange commented on README.md
> +We use GitHub:Issues for tracking issues with this connector. You can report new issues at this link http://github.com/mulesoft/sentry/issues.
@luizalfredo23 this is the default content generated for this file, right? We need to enter the proper README information for this connector. You have to provide adequate documentation if you want to make this project open source.

2018-07-16 14:50 UTC, hprange commented on src/main/java/br/com/doit/connector/sentry/ConnectionManagementStrategy.java
> +	 * Desconnect client
@luizalfredo23 small typo.

2018-07-16 14:50 UTC, hprange commented on src/main/java/br/com/doit/connector/sentry/SentryConnector.java
> +public class SentryConnector {
@luizalfredo23 we need to write proper documentation if we want to make this project open source. What you think about writing Javadocs for this class? We can take a look at other plugins for inspiration.

2018-07-16 14:50 UTC, hprange commented on src/main/java/br/com/doit/connector/sentry/SentryConnector.java
> +		}
@luizalfredo23 we need to set a code format standard before we publish the code.

2018-07-17 18:13 UTC, hprange approved these changes

2018-10-02 17:15 UTC, merged